---
- include_tasks: unpack.yml

- name: git add all new files
  shell: git add -A
  args:
    chdir: "{{ item.git_repo_path }}"

- name: git status
  shell: git status
  args:
    chdir: "{{ item.git_repo_path }}"
  register: git_add_status

- name: git username
  shell: git config user.name "{{ item.git_username }}"
  args:
    chdir: "{{ item.git_repo_path }}"
  when: item.git_username is defined

- name: git email
  shell: git config user.email "{{ item.git_email }}"
  args:
    chdir: "{{ item.git_repo_path }}"
  when: item.git_email is defined

- name: git commit
  shell: git commit -a -m "'{{ item.git_msg }}'"
  args:
    chdir: "{{ item.git_repo_path }}"
  ignore_errors: true

- name: git wrapper
  copy:
    dest: "{{ playbook_dir }}/.ssh/ssh"
    content: "ssh -i {{ git_temp_file.path }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $*"
    mode: 0700

- name: tag repository with version
  #Use static value versionTag-${REPO NAME} to map git version number from concord form input to correct repo variable
  shell: git tag -f {{ lookup('vars', 'versionTag-' + item.name) }}
  args:
    chdir: "{{ item.git_repo_path }}"
  ignore_errors: true

- name: git push
  shell: git push origin {{ item.version }} --force --tags 
  args:
    chdir: "{{ item.git_repo_path }}"
  environment:
    GIT_SSH: "{{ playbook_dir }}/.ssh/ssh"

- name: git status
  shell: git status
  args:
    chdir: "{{ item.git_repo_path }}"
  register: git_add_status

- include_tasks: cleanup_keys.yml
