---
- name: ATC AS3 Deploy
  hosts: ansiblegroup
  connection: local
  vars:
    provider:
      server: "{{ data.mgmtaddress }}"
      user: admin
      password: "{{ f5adminpassword }}"
      validate_certs: false
      server_port: 443
  gather_facts: false
  any_errors_fatal: true

  tasks:

    - name: Build AS3 declaration
      template:
        src: "{{ playbook_dir }}/templates/as3.j2"
        dest: "{{ playbook_dir }}/templates/as3-{{ inventory_hostname }}.json"

    - name: Deploy the AS3 service configuration
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_service: AS3
        atc_method: POST
        atc_declaration_file: "{{ playbook_dir }}/templates/as3-{{ inventory_hostname }}.json"
        